title: nanhu
lang: en
description: Nanhu User Documentation

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

